### ISSUE TITLE
Integration test and e2e test are both failing

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#1009]
**Describe the bug**

[Integration test](https://github.com/Qiskit/qiskit-ibm-runtime/actions/workflows/integration-tests.yml) has been failing for >3 weeks now, and [e2e](https://github.com/Qiskit/qiskit-ibm-runtime/actions/workflows/e2e-tests.yml) for 1 week. 

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by kt474** [comment]
Current failing tests:

`test_all_resilience_levels`: failing due to recent update on primitives side, it will be fixed by  qiskit-ibm-primitives issue 184 (related to #1048)

`test_cancel_job_queued`, `test_delete_job_queued`: cancel request is timing out, will open an issue on the server side

**Comment by jyu00** [comment]
Reopening since integration tests are still failing.

**Comment by kt474** [comment]
All integration tests passing on staging and production https://github.com/Qiskit/qiskit-ibm-runtime/actions/runs/6256997980 for the first time in a while. 

Will continue to keep on eye on the tests - it's a bit tough to have all the tests passing in staging in the quantum channel due to all the constant changes on the IQP side.

**Comment by kt474** [comment]
Integration tests have been passing on both channels, both staging and prod for a week - https://github.com/Qiskit/qiskit-ibm-runtime/actions/workflows/integration-tests.yml

I'll reopen this if they start failing consistently again
