### ISSUE TITLE
Verify test coverage

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#109]
**What is the expected feature or enhancement?**

Since there was a lot of rewrite and reusing old test cases, we should ensure the test cases provide sufficient coverage. This can be done manually or use some kind of tool as mentioned in #22.

**Acceptance criteria**

Verify there is sufficient test coverage.

**Comment by daka1510** [comment]
https://github.com/Qiskit/qiskit-ibm-runtime/pull/110 will enable code coverage reports for both, unit and integration tests. Let's continue to use https://github.com/Qiskit/qiskit-ibm-runtime/issues/22 as a follow-up to make it fancier and easier to spot trends over time (e.g. by adding coveralls integration, ...). In a first step we need to manually download a workflow artifact to review coverage metrics. This is not ideal but probably a first step towards betters insights.

What remains to be done to meet the acceptance criteria here
- review the unit and integration test coverage reports (see https://github.com/Qiskit/qiskit-ibm-runtime/pull/110#issuecomment-1016418481 for details)
- decide if the current coverage metrics are "sufficient"
- if necessary: identify improvement areas as needed and prioritize follow-up tasks

**Comment by daka1510** [comment]
Let's pick up work here again as soon as the referenced PR (#110) is integrated **and** the push tests do no longer consistently fail (tracked via #93).

**Comment by daka1510** [comment]
Gathered test coverage information from one of the rare successful integration test runs  to unblock working on this issue:
[Unit test coverage report - python3.9-ubuntu-latest.zip](https://github.com/Qiskit/qiskit-ibm-runtime/files/7914717/Unit.test.coverage.report.-.python3.9-ubuntu-latest.zip)
[Integration test coverage report - legacy-production.zip](https://github.com/Qiskit/qiskit-ibm-runtime/files/7914718/Integration.test.coverage.report.-.legacy-production.zip)
[Integration test coverage report - cloud-production.zip](https://github.com/Qiskit/qiskit-ibm-runtime/files/7914719/Integration.test.coverage.report.-.cloud-production.zip)

Downloaded from a [CI run](https://github.com/daka1510/qiskit-ibm-runtime/actions/runs/1728894685) of https://github.com/Qiskit/qiskit-ibm-runtime/pull/114

**Comment by daka1510** [comment]
### Data
Coverage Report - Unit Tests
![image](https://user-images.githubusercontent.com/16404496/150552541-8fd80e28-5e3b-46d9-8d05-92f2bf83b76c.png)

Coverage Report - Integration tests run against IBM Quantum
![image](https://user-images.githubusercontent.com/16404496/150552685-d0afe29b-32db-4e67-8bd5-5943ec68cc72.png)

Coverage Report - Integration tests run against IBM Cloud
![image](https://user-images.githubusercontent.com/16404496/150552773-cd2bb29f-0536-4e8e-ab99-ce6025ec41c7.png)

### Assessment
- Overall test coverage 
  - 57% for unit tests: 57%
  - 62% for integration tests against IBM Cloud
  - 66% for integration tests against IBM Quantum
- The public API entrpoints in (`ibm_runtime_service`) are well-covered (80-89%)
- Modules with little to now test coverage have not yet been enabled yet (`visualization` / `jupyter`), should improve via https://github.com/Qiskit/qiskit-ibm-runtime/issues/111 and https://github.com/Qiskit/qiskit-ibm-runtime/issues/112 

Though we can always improve, I personally think we're good for a first release and these reports along with the planned [enhancements](https://github.com/Qiskit/qiskit-ibm-runtime/issues/22) will make sure we keep an eye on coverage metrics anyway.

@jyu00, @rathishcholarajan anything else you see as an open to do here? Otherwise, can we close it?
