### ISSUE TITLE
Reporting unit test coverage to coveralls.io is failing

### ISSUE THREAD

**Issue by rathishcholarajan** [Qiskit/qiskit-ibm-runtime#157]
**Describe the bug**
Reporting unit test coverage to coveralls.io is failing https://github.com/Qiskit/qiskit-ibm-runtime/runs/5278880750?check_suite_focus=true
Do we want to fail the build in this case? Can we do any retries?

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **Qiskit IBM Runtime version**:
- **Python version**:
- **Operating system**:

**Comment by daka1510** [comment]
Just checked. Coverage reporting failed intermittently 3 days ago with two different types of response codes:

```
Run coverallsapp/github-action@1.1.3
Using lcov file: coverage.lcov
Error: Bad response: 408 
```

```
Run coverallsapp/github-action@1.1.3
Using lcov file: coverage.lcov
Error: Bad response: 504 
```

It ran reliably in subsequent [CI runs](https://github.com/Qiskit/qiskit-ibm-runtime/actions/workflows/ci.yml) and I could not find any issues on https://status.coveralls.io/.

> Do we want to fail the build in this case? 

My persoal view: let's close this issue for now as everything runs stable but keep an eye on coveralls API stability. If we see this more frequently, we can discuss options to make it an optional step that is allowed to silently fail.

> Can we do any retries?
I don't see an _easy_ way because we use https://github.com/coverallsapp/github-action which does not offer a retry configuration option.

**Comment by daka1510** [comment]
@rathishcholarajan do you agree to close it for now (see above for details) and follow up as needed when it happens more frequently?
