### ISSUE TITLE
Dump the running time or outcome of "each shot" in an experiment.

### ISSUE THREAD

**Issue by alan23273850** [Qiskit/qiskit-ibm-runtime#1622]
### What should we add?

Dump the running time or outcome of "each shot" in an experiment. The current version of Qiskit seems not to have this feature. A former version with option "memory=True" can only dump outcomes but not running times. Thank you everyone!

**Comment by ihincks** [comment]
I'm not familiar with this feature. What format would this timing information be specified in, and what exactly is it timing? Like a timestamp for each shot?

**Comment by alan23273850** [comment]
My timing means the total running time of a quantum circuit in each shot. I've participated in some talk where the speaker claims that if this information can be printed, then it would be very helpful to his research. Is it possible for IBM backends? Thanks again!

**Comment by jyu00** [comment]
Exactly what kind of per-shot running time are you looking for? If it's just gate time (i.e. time needed to process all the gates), then you can already calculate that information, as we publish the gate & readout lengths in backend properties. If you want to include the time the quantum program is loaded into control electronics, then there isn't really a "per shot" time since some operations (like load) only happens once. 

By the way, in case it wasn't obvious, SamplerV2 already gives you per shot measurement (similar to the old `memory=True`).

**Comment by jyu00** [comment]
Closing since there doesn't seem to be further questions.
