### ISSUE TITLE
Allow users to suppress mitigation with SamplerV2

### ISSUE THREAD

**Issue by yaelbh** [Qiskit/qiskit-ibm-runtime#1680]
To my understanding, in the absence of resiliency level, the way to suppress any kind of mitigation with SamplerV2 is by
```python
sampler.options.twirling.enable_measure = False
```

It took me quite some time to figure it out from the docs. I had to go through all the sampler options and check their default values.

There are two options:
1. Improve the documentation to include this use case.
2. Add an option like `suppress_mitgation` to the interface.

**Comment by jyu00** [comment]
Instead of having another option that users need to look though docs and find, wouldn't it be better to just make it explicit in the docs? Like having a section telling you what settings are needed to completely turn off any error mitigation / suppression.

**Comment by yaelbh** [comment]
Yes, this is Option 1.

**Comment by jyu00** [comment]
oh sorry I only read the title. 

I opened [this issue](https://github.com/Qiskit/documentation/issues/1453) for doc update.

**Comment by ihincks** [comment]
This is maybe more a nit than anything, but I wouldn't classify measurement twirling as mitigation. In my view, error mitigation protocols are broadly any strategy that improves results by incurring extra QPU usage combined with post-processing. Measurement twirling, assuming the stack is efficient, uses the same resources as no measurement twirling. I'd call it noise tailoring (or suppression) because it suppresses coherent bits of the noise model.

**Comment by yaelbh** [comment]
In view of the issue that @jyu00 has opened, can we then close this one?

**Comment by jyu00** [comment]
The [doc update](https://docs.quantum.ibm.com/run/configure-error-mitigation#turn-off-all-error-mitigation-and-error-suppression) is now live, so let's close this. Note that there is more work in progress to make the options easier to find.
