### ISSUE TITLE
Import error in "qiskit_runtime_vqe_program.ipynb"

### ISSUE THREAD

**Issue by snuffkin** [Qiskit/qiskit-ibm-runtime#208]
**Describe the bug**
There are some wrong import statements in this notebook.
Therefore, an import error will occur when executing it.
https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/docs/tutorials/sample_vqe_program/qiskit_runtime_vqe_program.ipynb

**Steps to reproduce**
An import error occurs in the following cells:

In[6]
`from qiskit_ibm_runtime import UserMessenger`
In[7]
`backend = Aer.backend("qasm_simulator")`
In[26]
`from qiskit_ibm_runtime import ResultDecoder`

**Expected behavior**
I modified it as follows and it works.

In[6]
`from qiskit_ibm_runtime.program import UserMessenger`
In[7]
`backend = Aer.get_backend("qasm_simulator")`
In[26]
`from qiskit_ibm_runtime.program import ResultDecoder`

Would it be better to send a pullrequest?

- **qiskit-ibm-runtime version**: 0.1.1
- **Python version**: 3.7.12
- **Operating system**: Linux

**Comment by daka1510** [comment]
Good catch, @snuffkin. 

I wonder if we should update the tutorial to import from `qiskit_ibm_runtime.program` or update [__init__.py](https://github.com/Qiskit/qiskit-ibm-runtime/blob/f10d088bfcb06d6f70df76d348257c22e06309d9/qiskit_ibm_runtime/__init__.py#L231-L240) with additional imports to not require changes in the tutorial. I prefer the latter option because that way consumers do not need to bother with the internal package structure. Thoughts, @rathishcholarajan?

Also, we should check if we can include this tutorial in our [e2e test runs](https://github.com/Qiskit/qiskit-ibm-runtime/blob/b56d7df95d34d90fd9708b71241cbe62e540b9ef/test/e2e/test_tutorials.py) that verify tutorial notebooks on a nightly basis.

**Comment by rathishcholarajan** [comment]
I'd prefer the latter option as well.

**Comment by arian-code** [comment]
Got struck on 
<pre><font color="#4E9A06">In [</font><font color="#8AE234"><b>5</b></font><font color="#4E9A06">]: </font><font color="#008700"><b>from</b></font> <font color="#729FCF"><b>qiskit_ibm_runtime</b></font> <font color="#008700"><b>import</b></font> UserMessenger
<font color="#CC0000">---------------------------------------------------------------------------</font>
<font color="#CC0000">ImportError</font>                               Traceback (most recent call last)
Input <font color="#4E9A06">In [5]</font>, in <font color="#06989A">&lt;cell line: 1&gt;</font><font color="#3465A4">()</font>
<font color="#4E9A06">----&gt; 1</font> <font color="#008700"><b>from</b></font> <font color="#0000FF"><b>qiskit_ibm_runtime</b></font> <font color="#008700"><b>import</b></font> UserMessenger

<font color="#CC0000">ImportError</font>: cannot import name &apos;UserMessenger&apos; from &apos;qiskit_ibm_runtime&apos; (/home/----/.local/lib/python3.8/site-packages/qiskit_ibm_runtime/__init__.py)

</pre>

Thankfully and painfully solved it by:
<pre><font color="#4E9A06">In [</font><font color="#8AE234"><b>8</b></font><font color="#4E9A06">]: </font><font color="#008700"><b>from</b></font> <font color="#729FCF"><b>qiskit_ibm_runtime.program</b></font> <font color="#008700"><b>import</b></font> UserMessenger

<font color="#4E9A06">In [</font><font color="#8AE234"><b>9</b></font><font color="#4E9A06">]: </font>
</pre>

Recommend update tutorial:
https://qiskit.org/documentation/partners/qiskit_ibm_runtime/tutorials/05_uploading_program.html
