### ISSUE TITLE
Shots can be negative

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#238]
**Describe the bug**
The `sampler` allows for negative values for shots, eg

```python
'run_options': {'shots': -1},
```

but returns results with 10k shots:

```python
{'header_metadata': {}, 'shots': 10000}
```

**Steps to reproduce**
Try using negative shots

**Expected behavior**
It should fail

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**: 0.2.0
- **Python version**: 3.10
- **Operating system**: OSX

**Comment by rathishcholarajan** [comment]
I've opened this issue in an internal repo where I believe this validation needs to happen. I will use this issue to add client side validation for `shots` only when using `IBMSampler` or `IBMEstimator` because it doesn't make sense to add client side validation when using the generic `service.run` that can be used to run any program.

**Comment by nonhermitian** [comment]
I think this was a different bug, so closing
