### ISSUE TITLE
Support for IBMQJobManager in QiskitRuntimeService

### ISSUE THREAD

**Issue by arian-code** [Qiskit/qiskit-ibm-runtime#325]
**What is the expected feature or enhancement?**

In the quantum computation module of QiskitRuntimeService, support is requested for IBMQJobManager.

This will enhance the ability to use higher number of qubit within each iteration of quantum call in the hybrid computing model.

**Acceptance criteria**
The main() subroutine should accept list of circuits and run using IBMQJobManager(). 

The results of the list of circuits should be published to the classical compute module for generating next iteration.

**Comment by robotAstray** [comment]
Hello @arian-code  is IBMQJobManager still being used? I'm interested in contributing to this issue. I'm uncertain about how to approach it if [IBMQJobManager](https://github.com/Qiskit/qiskit-ibmq-provider/blob/master/qiskit/providers/ibmq/managed/ibmqjobmanager.py) is no longer in use. Since the repository containing the class IBMJobManager has been archived on  July the 28th , I'm unsure is this issue is still valid/open.
