### ISSUE TITLE
Impossible to bypass transpilation in Estimator without large effort

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-runtime#338]
**What is the expected feature or enhancement?**
Suppose that I want to bypass the transpilation step in the `Estimator`.  It could be because I have a custom set of passes and / or perhaps that I do not want to pay the IBM Cloud time for something that can be done locally.  Is there a way to do that?

Suppose I start with this circuit with no measurements like the `Estimator` needs:

```python

N = 6
qc = QuantumCircuit(N)
qc.x(N-1)
qc.h(range(N))
qc.cx(range(N-1),N-1)
qc.h(range(N-1))
```

If I transpile the circuit:

```python

trans_qc = transpile(qc, backend)

```

then I have possible swap mapped by qubits to different positions.  Without the measurements attached, I have no way of knowing which permutation was generated, although a PR detailing how to do this has been up for almost a year now: https://github.com/Qiskit/qiskit-terra/pull/6827.  So I must first go back and add measurements to the circuit that does not have them, first noting that I must measure all qubits and pass any observables with `I` operators at the indices that I do not care about those qubits (in this example the target of all the cx gates) and then transpile again:

```python
meas_qc = qc.measure_all(inplace=False)
trans_meas_qc = transpile(meas_qc, backend)
```

Now I need to find which qubits correspond to which measured bits.  Now luckily Qiskit has some early M3 code (https://github.com/Qiskit-Partners/mthree/blob/0be84f79a29fc2a654db45582f8ce6d53e03b20d/mthree/utils.py#L32) that was added for the initial Runtime that allows one to find this:

```python
from qiskit.primitives.utils import final_measurement_mapping
mapping = final_measurement_mapping(trans_meas_qc)
```

Now one would have to take this mapping information and use it to create the necessary observables.  If all the qubit operators are then same then I just need to pad over all the qubits on the machine:

```python
op_str = "".join(['Z' if qu in qubits else 'I' for qu in range(backend.configuration().num_qubits)])

op = Pauli(op_str)
```

And finally, because I do not want my random swap mapping to change, I once again need to strip the circuit of the measurements:

```python

final_qc = trans_meas_qc.remove_final_measurements(inplace=False)

``` 

This is obviously a ton of work, and is not something that anyone should have to go through in order to transpile locally.  Because transpilation costs scale very poorly, the ability to bypass the cloud transpiler becomes more important over time.

**Acceptance criteria**

I do not have to do the above.

**Comment by nonhermitian** [comment]
This is coming back to haunt me again when trying to add dynamical decoupling to circuits for the estimator.

**Comment by mrossinek** [comment]
Thanks @nonhermitian for linking to this issue over from Terra! This is indeed more of what I was experiencing. Although I did not have it "as simple" as you because in fact my operator did not fulfill this condition:

> If all the qubit operators are then same then I just need to pad over all the qubits on the machine:

That is why I ended up using the private `_layout` attribute of my transpiled `QuantumCircuit` to map the virtual qubits of my operator to an expanded operator matching the size of my physical device. But reading your scenario above, that does indeed not take into account of any SWAP operations performed down the road (which for my use-case was fine since I did not have any but this is obviously not true in general).

<hr/>

All that is to say: how is this being handled on the server side? Surely they must have a way of "expanding" the operators to the correct physical locations? Is this done via transformations to the circuit level which in a scenario like this would need to be reversed?
Since the server side must be dealing with this in one way or another, maybe it is possible to extract whatever code that does and make it a standalone utility for endusers :thinking:

**Comment by ikkoham** [comment]
I implemented utility function `transpire_operator` for this issue: https://github.com/Qiskit/qiskit-terra/pull/9988

Unfortunately, I can't put it in the Terra 0.24 release, so I'm putting it in 0.25, but the function is not that big, so I expect to copy and paste and use it. For example,
```python
op = SparsePauliOp("Z" * N)
trans_op = transpile_operator(op, trans_qc.layout, qc.qubits)

result = BackendEstimator(backend=AerSimulator()).run(trans_qc, trans_op).result()
```
