### ISSUE TITLE
Automatically generate a runtime program JSON schema from the source code

### ISSUE THREAD

**Issue by rathishcholarajan** [Qiskit/qiskit-ibm-runtime#349]
**What is the expected feature or enhancement?**
https://gist.github.ibm.com/Blake-Johnson/b00470c6658c5fe5a9c603abce50371e

**Acceptance criteria**

**Comment by renier** [comment]
Since the only thing required is name when you upload a program, can this be translated into the following options?

* `def upload_from_file(self, path, max_timeout=600)` - where the name is derived from the file name and it can also fill out the schema.
* `def upload(self, name, program, max_timeout=600)` - simple version.
* `def upload_func(self, func, max_timeout=600)` - as the first one, but the func reference is already loaded (maybe defined in the same file). so you can introspect it for the name, and the rest of the schema if possible. Can the program body be read in as text from that?

**Comment by kt474** [comment]
> Since the only thing required is name when you upload a program, can this be translated into the following options?
> 
> * `def upload_from_file(self, path, max_timeout=600)` - where the name is derived from the file name and it can also fill out the schema.
> * `def upload(self, name, program, max_timeout=600)` - simple version.
> * `def upload_func(self, func, max_timeout=600)` - as the first one, but the func reference is already loaded (maybe defined in the same file). so you can introspect it for the name, and the rest of the schema if possible. Can the program body be read in as text from that?

There are a couple ways this can be implemented. I'm not sure we need 3 separate methods for uploading programs- would it not be more simple to keep the current `service.upload_program()` and just have it automatically generate the schema if one is not given? 

This way, a new method `build_json_metadata` could also be called separately if users want to generate a barebones schema and then make edits.

**Comment by kt474** [comment]
no longer necessary, closing
