### ISSUE TITLE
Sampler returns SamplerResult with dict

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit-ibm-runtime#362]
**Describe the bug**

Sampler returns SamplerResult with a list of dict. However, it should be SamplerResult with a list of QuasiDistribution.
See https://github.com/Qiskit/qiskit-terra/blob/df54ae26d6125bee671ad27f4d412a92912aad1a/qiskit/primitives/sampler_result.py#L42 for detail.

====
This may cause bugs in the future. In particular, applications will be written assuming the type.

**Comment by rathishcholarajan** [comment]
@ikkoham Any ideas on how to fix this without making it a breaking change? Users would have to now use `binary_probabilities()` method to get the same result.

**Comment by ikkoham** [comment]
It would be difficult not to fix this without API breaking.
I think we can convert dict to QuasiDistribution at this line:
https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/sampler.py#L211

And user should use `binary_probabilities()` method. If you don't like this interface, it would be nice to define `QuasiDistribution.__str__` in Terra. But, it might be costly...

Or we can extend SamplerResult to have `QuasiDistribution | dict`. But I don't think it's a good idea, because users will have to do some conditional branching.

**Comment by rathishcholarajan** [comment]
Thanks Ikko! I also don't see a way to make it a non-breaking change... I think the best option is to make SamplerResult return `QuasiDistribution | dict` because I have spoken to one expert user in the past who preferred the output returned by `binary_probabilities()`, which is a dict and that is what the current API returns.. also if anyone wants to get a QuasiDistribution from it, it is easy to do... what do you think?

**Comment by ikkoham** [comment]
At least, it is undesirable to have a situation where a conditional branch always occurs when someone tries to use SamplerResult. This is, for example, the situation where all the code in `qiskit.algorithms` has a conditional branch.
I would rather change the `SamplerResult.quasi_dists`'s type to dict than do have `Union`. This is also API breaking of SamplerResult. We need to discuss this problem with @levbishop or @ajavadia.

**Comment by t-imamichi** [comment]
I see the current dict format of `quasi_dists` is more intuitive to users. `QuasiDistribution` is not so intuitive because it does not have information of the number of qubits. So, users need to set appropriate number of qubits to call `binary_probabilities`.
One possible extension of `QuasiDistribution` is as follows. Then, the output message will be as informative as the current dict.
1. `QuasiDistribution` accepts number of qubits as a constructor argument, i.e., `dist = QuasiDistribution(..., num_qubits=3)`
2. Implements `QuasiDistribution.{__str__, __repr__}` with `binary_probabilities`.

**Comment by nonhermitian** [comment]
The problem actually lies in the refactor of the `QuasiDistribution` class to not store its data as bit-strings. The class should be modified to have the number of qubits stored when passed a dict of bit-strings.  M3 always returns bit-strings, since I need them for expvals, so such a change would work here.

**Comment by t-imamichi** [comment]
Thanks, @nonhermitian. I made a PR to update `ProbDistribution` and `QuasiDistribution` to store bit-string data. Could you take a look at it? https://github.com/Qiskit/qiskit-terra/pull/8464
