### ISSUE TITLE
Wrong text in Docs of user-transpiled-circuits.ipynb

### ISSUE THREAD

**Issue by kifumi** [Qiskit/qiskit-ibm-runtime#406]
**Describe the bug**
In the text below of docs tutorial [user-transpiled-circuits.ipynb](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/docs/tutorials/user-transpiled-circuits.ipynb) file, the "right" and "left" look like the opposite.

> Finally, we can plot the results from the device runs against the ideal distribution. For each measured string, the leftmost bar is the ideal distribution, the central bar is the circuit transpiled with optimization_level=3, and the rightmost bar is the circuit transpiled with optimization_level=0).

**Steps to reproduce**

**Expected behavior**

**Suggested solutions**

**Additional Information**

- **qiskit-ibm-runtime version**:
- **Python version**:
- **Operating system**:

**Comment by HuangJunye** [comment]
Thanks for spotting the error. In addition, there are 4 bars but the description refers to 3 bars (left, central and right).

If I remember correctly, this is because the plot initially only have 3 bars, the fourth (optimization level 3 + dynamical decoupling) was added later and the text was not updated accordingly.

@frankharkins would you like to update this section?

**Comment by rathishcholarajan** [comment]
@lerongil @HuangJunye any updates on this?
