### ISSUE TITLE
Reenable disabled pylint rules that we don't consider too verbose

### ISSUE THREAD

**Issue by daka1510** [Qiskit/qiskit-ibm-runtime#42]
**What is the expected feature or enhancement?**
This is a follow-up item for https://github.com/Qiskit/qiskit-ibm-runtime/pull/40#discussion_r760150252. 

We have disabled a few pylint rules to unblock an update to the latest Python / pylint version. Below rules have been marked with a TODO and should be reenabled when the code has been fixed:
- [x] arguments-renamed (stay disabled)
- [ ] bad-mcs-classmethod-argument,  
- [x] consider-iterating-dictionary, 
- [x] consider-using-dict-items,     
- [x] consider-using-f-string (stay disabled),       
- [ ] consider-using-with,           
- [x] differing-param-doc,           
- [x] docstring-first-line-empty (stay disabled),    
- [x] f-string-without-interpolation,
- [ ] invalid-name,                  
- [x] missing-param-doc (stay disabled),             
- [x] missing-type-doc,              
- [ ] no-member,                     
- [ ] raise-missing-from,            
- [x] redundant-returns-doc,         
- [ ] super-with-arguments,          
- [ ] unspecified-encoding,          
- [x] use-dict-literal,              
- [x] use-list-literal,

**Comment by kt474** [comment]
`arguments-renamed`: complains that "o" has been overridden by "obj" [here](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/utils/json.py#L182), also "run_input" -> "circuits" in program_backend.py
`bad-mcs-classmethod-argument`: suggests renaming mcs -> cls [here](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/test/test_tutorials.py#L35)
`consider-using-f-string`: 50+ suggestions of using f strings instead of `str.format()`
`consider-using-with`: 8 suggestions to use `with` in places like [this](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/test/utils/account.py#L112)
 `docstring-first-line-empty`: complains that the first line in our init files is "empty" [link](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/__init__.py#L13)
`invalid-name`: complains about one and two letter variable names [here](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/test/test_data_serialization.py#L131)
