### ISSUE TITLE
Tests started failing without code change in qiskit-ibm-runtime

### ISSUE THREAD

**Issue by daka1510** [Qiskit/qiskit-ibm-runtime#59]
**Describe the bug**
6 test cases started failing without code changes in qiskit-ibm-runtime.
![image](https://user-images.githubusercontent.com/16404496/145823301-07f23194-a080-4001-bb60-3c5da6c03a1c.png)

**Steps to reproduce**
Run PR tests

**Preliminary analysis**
Inspected the objects where `self.assertEqual` now fails with the aid of the debugger. In the failing cases `op.coeff != decoded.coeff`. 
![image](https://user-images.githubusercontent.com/16404496/145837951-ed025dc9-4328-43a7-a1f0-27c47725d552.png)
- Tests started failing in the last 2-3 days
- Test regression likely caused by one of the changes listed in https://github.com/Qiskit/qiskit-terra/releases/tag/0.19.1 because `qiskit-terra` is not pinned to a specific version in `qiskit-ibm-runtime` ([code](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/requirements.txt#L1))
  - most suspicious change is https://github.com/Qiskit/qiskit-terra/pull/7374

**Comment by daka1510** [comment]
@mtreinish - do you happen to know how to properly fix this? Do we need to update the [encoder/decoder code](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/utils/json.py#L173-L273)?

**Comment by jakelishman** [comment]
This looks severely like a bug in the QPY serialisation/deserialisation - on close inspection, the UUIDs for the read parameters are offset by two bytes compared to the inputs.  I'm not entirely sure how that's managed to happen without _completely_ failing all tests, but there we are.  I'll look into getting it fixed in Terra ASAP, and then look to release a 0.19.2.

**Comment by jakelishman** [comment]
Ah no, sorry - I'm wrong.  In this case it's that you're using an old version of the parameter expression unpacking.  There was a new QPY serialisation format, and since you're using internal functions of `qpy_serialization`, there wasn't any stability there.

This is possible to fix, but I think you'll have to detect the version of Terra, because you need to know whether to set your reader to `_read_parameter_expression` or `_read_parameter_expression_v3`.  I'll make a PR for you.
