### ISSUE TITLE
Different defaults for error mitigation/suppression for noiseless backends

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#643]
**What is the expected feature or enhancement?**

Current default options for the primitives are:

```
optimization_level = 3
resilience_level = 1
```

These options add a processing overhead for error suppression and error mitigation. When using noiseless devices, the overhead doesn't bring any additional improvements. We should consider using different defaults when using noiseless devices (i.e. simulator without noise model)

**Acceptance criteria**

**Comment by merav-aharoni** [comment]
I'd like to assign myself to this issue, but couldn't find the settings button to assign myself.

**Comment by merav-aharoni** [comment]
@kt474 , @jyu00 - I would like your advice on how to implement this. At first I thought I could simply override the value for `optimization_level` in `sampler.py` (and probably in `estimator.py` - I didn't look there yet), because that is the time where we are aware of the circuit and can check whether it is simulation and if there is a noise model.
However, I see that I cannot differentiate between the case where the user specified an `optimization_level` of 3, and the case where he didn't specify an `optimization_level` because the default is defined as 3 in `Options`. I assume that if the user explicitly specified the `optimization_level` then we don't want to override his value. We override only if we are using the default.
So my conclusion is that `Options()` should actually create an empty object, and that we should create a `default_options` with all the default values, so that we can differentiate the two. The merge of the two sets of options should probably take place in `Sampler` (and maybe in Estimator), but I haven't looked so far yet.
Please let me know if this makes sense or if I am missing something. This is probably a bigger fix than what you had in mind.

**Comment by kt474** [comment]
Yeah I see the issue here, there is no way to differentiate between `Options()` and `Options(optimization_level=3)` 

This is probably a bigger change than what we originally had in mind but I can't think of any other solutions - @jyu00 thoughts?

**Comment by jyu00** [comment]
We can just change the [default `optimization_level`](https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/options/options.py#L84) to `None`, right? Then update it in Sampler/Estimator `run` to the default value if it's still `None`.

**Comment by merav-aharoni** [comment]
@jyu00 - that sounds like a good idea to me.
