### ISSUE TITLE
don't override explicit max_execution_time of first job

### ISSUE THREAD

**Issue by cpkurotori** [Qiskit/qiskit-ibm-runtime#675]
https://github.com/Qiskit/qiskit-ibm-runtime/blob/88c06a1935eac62c102b47e624d6daf35118b44f/qiskit_ibm_runtime/session.py#L146-L149

currently during `session.run()` the cost of the first job is set to the session max_time regardless of if `max_execution_time` was explicitly set  in the job options

```
 if not self._session_id and "max_execution_time" not in options: 
     options["max_execution_time"] = self._max_time 
```

this may be ultimately be replaced by fixes for #670 if we don't use `max_time` as `max_execution_time` but instead as `session_limit`. However, these changes should still be fixed since any first job session time will have it's max execution overwritten (even if `max_time` is None, if `max_execution_time` is set on the job, it will be replaced by `None`.

**Comment by jyu00** [comment]
Is this a real bug? `max_execution_time` is **not** a job-level attribute, since you can't change the session timeout in the middle of a session. It should only be set when a session is first created (i.e. in `__init__`). It being the timeout of the first job is just how it's implemented internally.

**Comment by kt474** [comment]
I don't think this is necessary anymore, closing for now
