### ISSUE TITLE
Remove deprecated features from >3 months ago and TODOs

### ISSUE THREAD

**Issue by jyu00** [Qiskit/qiskit-ibm-runtime#784]
**What is the expected feature or enhancement?**

Many features were deprecated in 0.7 release and can be removed now. In light of [this issue](https://github.com/Qiskit/qiskit-ibm-provider/issues/550), the TODOs in the code should be reviewed and actions taken accordingly. 

**Acceptance criteria**

- Remove features that had sufficient deprecation period per Qiskit's [deprecation policy](https://qiskit.org/documentation/deprecation_policy.html#:~:text=We%20consider%20a%20feature%20marked,merge%20new%20functionality%20to%20it.)
- Review/fix all TODOs

**Comment by merav-aharoni** [comment]
@kt474 - deprecated code for which versions can be removed?

**Comment by kt474** [comment]
Yes, it is a bit confusing - originally, I believe we wanted all options passed into `session.run()` to be honored, but in terms of `backend`, it never worked because sessions don't support cross multiple backends. This deprecation message was meant to just inform users not to pass in a backend in the options and the doc strings say the same thing. I'm ok with just leaving this deprecation message for now, as I don't believe any users are doing this anymore anyway. 

I agree that ideally, `backend` is not an option, but it would be a relatively big change unrelated to this original issue

**Comment by jyu00** [comment]
We can just make a copy of the input `options` before adding `backend` to it. We really shouldn't be modifying a user's variable to begin with anyway. 

We can remove/privatize both `session.run()` and `service.run()` once everything becomes primitives only (i.e. no more custom programs).

**Comment by kt474** [comment]
I believe #1093 handles the last deprecation warning we can remove, after it's in we can close this issue

**Comment by jyu00** [comment]
closing this, but as part of the release process we should always check if there are deprecated features that can be removed.
